### ISSUE TITLE
Geo

### ISSUE THREAD

**Issue by sacredland** [oddluck/limnoria-plugins#13]
pip install geoip2

Installing collected packages: urllib3, idna, certifi, chardet, requests, ipaddress, maxminddb, geoip2
Successfully installed certifi-2019.11.28 chardet-3.0.4 geoip2-3.0.0 idna-2.9 ipaddress-1.0.23 maxminddb-1.5.2 requests-2.23.0 urllib3-1.25.8

<admin> -load geo
<bot> admin: Error: The Geo plugin requires geoip2 be installed.  Load aborted.

I installed geopip2, from the user & as admin on the box. The bot still reply it is not, even after reboot.

**Comment by sacredland** [comment]
fixed it with
sudo apt install python3-geoip2

**Comment by oddluck** [comment]
That's odd, pretty sure I installed it with pip myself, but it's been a while. Did you try restarting the bot after installing with pip? Sometimes a restart will clear those import errors up if the packages are there but not being recognized.
