### ISSUE TITLE
Corona

### ISSUE THREAD

**Issue by sacredland** [oddluck/limnoria-plugins#14]
Hi, with the new update we lost the ability to see canadian province status. We had it before.. ;/

**Comment by oddluck** [comment]
If you'd like to use the old version of the plugin using JHU data it's been re-added as [CoronaLight](https://github.com/oddluck/limnoria-plugins/tree/master/CoronaLight)

**Comment by sacredland** [comment]
Ok well I like the new one with rank/more stats, and someone (grep) told me you’ll update the new one to have also the option of canadian province. So i was waiting it but if it’s note the case i guess i’ll use the old one :/

**Comment by Estella** [comment]
Thanks oddluck this is great to have both data sources, did a minor change:

422:    def coronalight(self, irc, msg, args, search):

To allow for both to be used same time.

**Comment by oddluck** [comment]
@Estella: you can just use the @rename command provided by limnoria core. e.g. @rename coronalight corona coronalight
@sacredland: The new data source does not offer Canadian province info. I might add multiple data sources to the plugin at some point but it's a lot of work as both sources use entirely different formats for storing their data.

**Comment by Estella** [comment]
@oddluck  ahh cool didn't know about that, thanks for providing these plugins to us, i'm a huge fan of your work on these =)

**Comment by sacredland** [comment]
> 
> 422: def coronalight(self, irc, msg, args, search):
> 
> To allow for both to be used same time.

@Estella use both, old and new?

**Comment by Estella** [comment]
@sacredland yes, I have both loaded, I like the old one for looking up Alberta, and the new one for world ones like USA/Italy/China

**Comment by oddluck** [comment]
@sacredland yes, you can use both, and either use the `aka` command to create an alias to `coronalight corona` or the `rename` command to avoid confusion between the two permanently. I have preliminary work done on adding an option to select sources in the the main Corona plugin, but it'll probably be a couple days before it's ready to be pushed to the repo (I also hate promising stuff that I may never finish). Also working on some other stuff like a `top10` and `news` command and will push a new Corona version when/if I it's completed.
