### ISSUE TITLE
corona top10 rank

### ISSUE THREAD

**Issue by sacredland** [oddluck/limnoria-plugins#15]
There's a little trouble with top10 rank:
<user> -corona usa
<Bot> **USA: World Rank: #2** | Cases: 300,028 (+22,867) (+8.3%) | Deaths: 8,137 (2.7%) (+733) (+9.9%) | Recovered: 14,464 (4.8%) | Active: 277,427 (271,111 Mild) (6,316 Serious) (97.7%/2.3%) | Cases/1M: 906 | Deaths/1M: 25 | Updated: 5.7m ago
<user> -corona --top10
<Bot> **#1: Total:** (1,169,323/62,730), #2: USA (300,028/8,137), #3: Spain (124,736/11,744), #4: Italy (124,632/15,362), #5: Germany (92,150/1,330), #6: France (82,165/6,507), #7: China (81,639/3,326), #8: Iran (55,743/3,452), #9: UK (41,903/4,313), #10: Turkey (20,921/425) | Updated: 5.8m ago

**Comment by oddluck** [comment]
Yeah, they added a World row as well as Total which threw off the rankings, fixed in latest commit.
