### ISSUE TITLE
Corona NZ Deaths/1M off by factor of ten

### ISSUE THREAD

**Issue by pajamian** [oddluck/limnoria-plugins#16]
https://www.worldometers.info/coronavirus/#countries shows deaths/1M as 0.2 for New Zealand, but the Corona plugin returns 2.

**Comment by tmannerm** [comment]
Seems to affect anything that has decimal point at least in death/1M column. For example, shows 5 for 0.5 in Russia and 1 for 0.1 in India.

**Comment by oddluck** [comment]
Thanks for noticing that, fixed in the [latest commit](https://github.com/oddluck/limnoria-plugins/commit/126bf48f0d7633d2c901f1fb729f9ca959fdc68c).
