### ISSUE TITLE
[Tweety] Allow --nort in tsearch

### ISSUE THREAD

**Issue by EvilOlaf** [oddluck/limnoria-plugins#20]
Hey there,

I would like to suggest to add the `--nort` switch to the `tsearch` command to suppress results that have been retweeted by someone else.

Thanks for reading.

Werner

**Comment by oddluck** [comment]
Sure. Added in commit https://github.com/oddluck/limnoria-plugins/commit/e038a805e150abcbff9a7678475706a0dedc3df3

**Comment by EvilOlaf** [comment]
Awesome. Will test this ASAP. Thank you.
