### ISSUE TITLE
SpiffyTitles - Twitch-API 

### ISSUE THREAD

**Issue by fred0r** [oddluck/limnoria-plugins#22]
Been using latest Version and configured `supybot.plugins.SpiffyTitles.twitch.clientID` to my Twitch ClientID.

Latest URL i used for testing was `https://www.twitch.tv/pietsmiet`

When pasting any Twitch-Url theres no Output to IRC, beside 'Twitch' and the Bot-Console shows:

`SpiffytTitles: Twitch Error: 401 Client Error: Unauthorized for url: https://api.twitch.tv/helix/streams?user_login=pietsmiet`

**Comment by fred0r** [comment]
>  `supybot.plugins.SpiffyTitles.twitch.clientID` to my Twitch ClientID.
> 
created that ID according to the readme.

**Comment by oddluck** [comment]
I'm aware of this issue. Twitch just recently changed the authorization method for their API and the twitch handler needs to be rewritten. Will fix when I get a chance.

https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

**Comment by oddluck** [comment]
Fixed in https://github.com/oddluck/limnoria-plugins/commit/32c8053d13d7b350a99f5260030153d2da45e7a7. Please see the updated README for instructions on how to set Client ID and Access Token https://github.com/oddluck/limnoria-plugins/tree/master/SpiffyTitles#twitch-handler

**Comment by fred0r** [comment]
Nice - works just fine - Thank you !
