### ISSUE TITLE
SpiffyTitles - Flood Protection

### ISSUE THREAD

**Issue by fred0r** [oddluck/limnoria-plugins#24]
It would be nice to be able to configure some Flood-Setting directly in SpiffyTitles.
Some Users paste plenty of URLs in the same Line and repeating this multiple Times.
Then the Bot seems to work through all these URLs, even when these are all the same, causing Spam in the Chan.

Checked AttackProtector and ChanTracker, but these 'only' work when the Bot is OP.

Would be nice if there are some SpiffyTitle-Variables to ignore these Users after 'n' URLs for 'n' Seconds.
Also a Check to not write the same Url-Title in 'n' Seconds, even when pasted from different Users.
Beside these, also nice would be, to be able to set something like overall 'n' URL-Announcements in Channel.
While thinking about it - some Variable for 'how many urls in one Line by User' are checked/displayed.

**Comment by oddluck** [comment]
See also: https://github.com/ProgVal/Limnoria/issues/1413

**Comment by fred0r** [comment]
thx to https://github.com/ncoevoet/ChanTracker/commit/41a9bd5eaac8b2d2996c719b85dfe8956bceecbf theres a possibility  to prevent this.
