### ISSUE TITLE
Tweety - suggestion: provide direct link to tweet

### ISSUE THREAD

**Issue by EvilOlaf** [oddluck/limnoria-plugins#34]
Hey there,

so far Tweety is running for quite a while now and it is working great. Thank you.

As a suggestion from users it would be nice if Tweety could provide a (shortened) directlink to the actual tweet by option. At the moment it only includes links that were actually a part the parsed tweet.

As always thanks for reading.

Cheers
Werner

**Comment by oddluck** [comment]
That's already an option. https://github.com/oddluck/limnoria-plugins/tree/master/Tweety#extras

config plugins.tweety.addshorturl True

**Comment by EvilOlaf** [comment]
Well...my bad. I was perfectly sure I had this option enabled already and it was designed to apply against URLs within tweets.
Sorry for the noise then.

I hope you had some peaceful holidays.

Cheers
Werner

**Comment by oddluck** [comment]
No worries. Happy holidays to you as well.
