### ISSUE TITLE
Spiffytitles - Youtube handler does not catch official Youtube shortened URLs

### ISSUE THREAD

**Issue by metaltermite** [oddluck/limnoria-plugins#36]
Youtube has had a Youtube [URL shortener](https://techcrunch.com/2009/12/21/youtube-url-shortener/) for a while. In a browser the short URLs can be accessed via the `share` link. The Youtube handler in SpiffyTittles isn't catching said shortened URLs.

Short URL: `https://youtu.be/[video id]`

**Comment by oddluck** [comment]
They work just fine for me.
