### ISSUE TITLE
Youtube is going to remove dislike counts from the API on 2021-12-13

### ISSUE THREAD

**Issue by progval** [oddluck/limnoria-plugins#45]
> 
> Subject: Important update from YouTube API Services: Making the dislike count private
> Date: Wed, 10 Nov 2021 09:28:34 -0800
> From: YouTube API Services <no-reply@youtube.com>
> Reply-To: YouTube API Services <no-reply@youtube.com>
> 
> 
> 
> YouTube
> 
> -----
> 
> 
> Dear YouTube API developer,
> 
> 
> We would like to inform you of upcoming changes to YouTube that will impact  the data available via the Data API starting December 13, 2021.
> 
> On November 10, YouTube will be making the public dislike count private.  Users will still be able to dislike videos, and creators will still have  access to the dislike counts for their own videos in YouTube Studio. Learn  more about this change in our  <https://notifications.google.com/g/p/AD-FnEzKe6JQVbVbeG2NZaj4WcCbJFyAkrIHR0B2SMzzo8EG0fq-aAZsWFhF0KGeJloPTdYD-C2svjrri5HzJGI6RkpppaRcRbJYvXQiyg5YoF6tp7T1p2C_ro7F3iKFeBrM6eUC-ZY>blog  post.
> 
> To make the dislike count private across the platform, we also will be  removing public access to the dislike count data via our API.
> 
> Here are details on how this will and will not affect the API:
> 
> - The  <https://notifications.google.com/g/p/AD-FnEz-R13SBgHfoFg_iGvdXPVkwGxB5gbdaUnDTBWsqh4yphWunNKvAukIiVNjFZLHpwe4mxZnBvJp6W4812hfGnjuD9bTei6yMWDn7oRavRQZ_8oTQnQEOAms0N9YamlqhyZgLrozp6Ixgd3R90igD5gIVXINWFljfe5KCP0a>dislike_count  field within the statistics part of the  <https://notifications.google.com/g/p/AD-FnEwfWWE2faMv0BArihHo8x_KdMwK-zfcd0C8YAY2iMWu_z1P0aEDixzgIUm3cBwQz9tiv9GV7gz3XaN7t4KpNyqFwROboGLi-VCeA4Zy76jyU07Fdmv1ZJwlVhY5BX2I___SnegclEUqYVSi6nSmsjJjxBcCW34FJb0AcISLnQ>video  resource will be omitted on calls to the  <https://notifications.google.com/g/p/AD-FnEyY0y0DKxJ4qzlUpSblR80iNF_niVwcSPLFUYBIuQuPokh1fig741AO9TcmhOESYOjPcvU-H-latXmPGF0zlavSG34uqoAPiUg_9VUNfQEyExYHyD_KfuZ4HtZzceePbUBd8ZJk-sKxsrlo>video.list  endpoint except in cases in which the request is being authenticated as a  user (such as the creator or the agent user) who owns the video that is  being requested.
> - The  <https://notifications.google.com/g/p/AD-FnEy7rXWQ8VA45K0X28ddZRpZgkJnWw_kVF3na6W1rOJs8TrF_lnRTnSeqw18cMhsWf3bOA37XfCP4nX9k5mDAMuBqBt6yMJlqahsXtpwLGjEQlnKZzUVcPLw8BxBN3utTAt9NqUSINvf>videos.rate  endpoint will be unaffected.
> - Developers who do not display dislike counts publicly and still need the  dislike count for their API client can apply to be put on an allow list for  an exemption.
> If you would like to apply for an exemption, you must complete this  <https://notifications.google.com/g/p/AD-FnEwjkNFtB2DNbAff1uoByI2RQ7TmkbX3hmzSNd473dehsulp2ed91m3hRDGjOJUzag2pshHufcUsJAWzarFJSMr-npYZpHb101nyROkgIugmnsHsXgIzRc_cIrxAlRoyy9X3nSPnDW03prIRjs87q5M9-Emztw-PhvSvBOuLgQ7QaRNSaeKj8q_ObGEtA5s2eUyiPkbyUPY>application  form. Otherwise, your access to public dislike count data via the Data API  will end on December 13, 2021.
> 
> As a reminder, you must agree to the  <https://notifications.google.com/g/p/AD-FnEztMF755NBRoVPNNqJ9XgsCk70je1fmZ-ZbTpJ7I0Hk8KZ64l6QRP4dWFPg2PsCLMoRoT-x_lvg5zKMEQW7NSBwhem3KGknPQlDBqu7e8FZj3oPjGfXwmeP_QXXDgNWbIYIuPb0B1MBmTX4wskDFjrDZA>terms  and  <https://notifications.google.com/g/p/AD-FnEx7kUL8BS5pRLLzYI1-luHc4PluJNaj7lKiOHzuYo_OHZ5Fl9DG5bF3BoBXxiBdBxyTINZg0Q7Q7P88Plow8JlRxf_rvqRG0SyikGy7s6K195tgSwx4QM7h2WAUj3mYHyjbeu3WpeMsOUc>policies  to access or use any YouTube API Services.
> 
> Thank you for being a YouTube API developer.
> 
> 
> 
> 
> 
> Sincerely, The YouTube API Services team
> 
> -----
> 
> 
> You received this mandatory email service announcement to update you about  important changes to your YouTube account.
> 
> (c) 2021 Google Ireland Ltd Gordon House, Barrow Street Dublin 4, Ireland

**Comment by oddluck** [comment]
Thanks, fortunately this won't break anything but I need to edit the default template config. When the change happens it will just show 0 dislikes and not break any functionality. The template is also editable so people can remove reference to the dislike variable themselves.
