### ISSUE TITLE
Lyrics Plugin is not a good url wikia no longer exists

### ISSUE THREAD

**Issue by d0rq** [oddluck/limnoria-plugins#50]
Hi, how to use say lyrics.com in this vs the one installed, ty!

**Comment by oddluck** [comment]
Yeah, unfortunately the wiki is no longer available, the replacement is no longer compatible and hostile to scraping (they want to show you advertisements). This plugin is permanently broken and will eventually be deleted. The whole thing would need to be rewritten with some easily accessible source if one even exists...
