### ISSUE TITLE
Tweety (help)

### ISSUE THREAD

**Issue by nukam0s** [oddluck/limnoria-plugins#53]
im getting this "ERROR: Something went wrong trying to search Twitter. (None)" with every request, is this something i did wrong or its a twitter side thing? anyone has it working? 

i set the tweety.consumerkeys/secret with my twitter "API Key and Secret" and the access ones with the "Access Token and Secret"  (hope that was the right way), runned the requirements with no errors also

(its the twitter free tier btw)

tyvm

**Comment by oddluck** [comment]
Twitter API is no longer free. This plugin is no longer supported.
