### ISSUE TITLE
IMDB not pulling rating score

### ISSUE THREAD

**Issue by DasClarky** [oddluck/limnoria-plugins#54]
I have noticed recently that the rating is no longer showing, just N/A, along with other things also showing N/A

^  IMDb  :: The Continental: From the World of John Wick (2023, United States, [TV-MA], Action, Crime, Thriller, N/A) :: IMDb: N/A | MC: None | RT: None :: Set in 1970s New York City, The Continental explores the origin of the iconic hotel-for-assassins centerpiece of the John Wick universe seen through the eyes and action of a young Winston Scott. :: Director: N/A :: Cast: Mel Gibson, Colin Woodell, Mishel Prada :: Writer: Greg Coolidge, Shawn

**Comment by oddluck** [comment]
The show literally just premiered yesterday... Give the database time to update. I can't will reviews into existence, just return what data is available, in this case, None Available aka N/A
