### ISSUE TITLE
SpiffyTitles doesn't work with Python 3.12 because they removed the 'imp' module

### ISSUE THREAD

**Issue by inhahe** [oddluck/limnoria-plugins#59]
I just walked someone through installing Limnoria and a few plugins on their computer, and I had them install Python 3.12 assuming it would work because YOLO (I use Python 3.11), and SpiffyTitles won't load because the 'imp' module is missing. A little research revealed that it was removed from Python in version 3.12 (in 3.11 it's apparently only deprecated). 

So I told her she had to install Python 3.11 and we'd have to do some things over again, or she could just use the 'Web' plugin. She's currently using the 'Web' plugin, but it doesn't seem to work for youtu.be links and who knows what else.
 
Also, btw, `!plugindownloader install oddluck SpiffyTitles` doesn't install the requirements. I don't know if that's SpiffyTitles' fault or if it's possible to make it work right, since I don't know the details of how !plugindownloader works.

**Comment by oddluck** [comment]
Thanks for pointing this out... Fixed in https://github.com/oddluck/limnoria-plugins/commit/5d1ca4bf8606a2386d2ce0899b3959fdf847a7ff

 PluginDowloader doesn't install plugin requirements, those need to be installed manually via command line.
