### ISSUE TITLE
On the ChatGPT plugin, the message parser command doesn't work

### ISSUE THREAD

**Issue by veebch** [oddluck/limnoria-plugins#64]
Hello there! Despite the warning about it not working, the plugin for chatgpt is working fine 

the +chat command works and results are being returned from chatgpt.

But:

@messageparser add "(?i)(.*BOT_NICK_HERE)(?:[:]*)(.*)" "chat $1$2"

seems to not be parsing the messages in chat that start with the name of the bot , followed by a colon.
 
Am I missing something obvious?

Thankyou!

**Comment by oddluck** [comment]
What is the value of @config reply.whenaddressedby.nick? If True (likey) set False.

**Comment by veebch** [comment]
It was True, setting to false fixed it.
